apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: nodejs-microservices-ticketing
build:
  local:
    push: false
  artifacts:
    - image: nhamonin/microservices-auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*'
            dest: .
  hooks:
    before:
      - command:
        - kubectl
        - delete
        - job
        - prisma-migrate-job
        - --ignore-not-found
manifests:
   rawYaml:
      - ./infra/k8s/*
