apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
stringData:
  MYSQL_ROOT_PASSWORD: my-root-password
  MYSQL_DATABASE: auth
  DATABASE_URL: mysql://root:my-root-password@auth-db-srv:3306/auth
