apiVersion: batch/v1
kind: Job
metadata:
  name: prisma-migrate-auth-job
spec:
  template:
    spec:
      initContainers:
        - name: check-auth-db
          image: busybox
          command:
            - /bin/sh
            - -c
            - >
              until nc -z -v -w30 auth-db-srv 3306; do
                echo "Waiting for database connection...";
                sleep 5;
              done
        - name: prisma-migrate-auth
          image: nhamonin/microservices-auth
          command: ['sh', '-c', 'npx prisma migrate deploy && npx prisma db seed']
          envFrom:
            - secretRef:
                name: auth-secret
      containers:
        - name: placeholder
          image: busybox
          command: ['sh', '-c', "echo 'Migration and seeding completed'; sleep 3600"]
      restartPolicy: Never
  backoffLimit: 4
